; Сгенерировано pyz80_compiler. Не редактировать.
RTYPE_PY_CODE_BANK0_PAGE EQU #F0
RTYPE_PY_ABI_STACK_SLOT_BYTES EQU 2
; ABI: pyz80-z80-stack-v1

PyZ80FT_BuildSpriteBatch EQU #96E4
PyZ80FT_BuildSpriteBatchFast EQU #96CE
PyZ80FT_FindHQTemplate EQU #884C
PyZ80FT_LogicalVertex EQU #81A5
PyZ80FT_LowerNativeX EQU #82AA
PyZ80FT_LowerNativeY EQU #83FC
PyZ80FT_QueueAcquire EQU #87C2
PyZ80FT_QueueAcquireFragment EQU #87E0
PyZ80FT_QueueCommit EQU #9BD1
PyZ80FT_QueueCommitFragment EQU #9CD5
PyZ80FT_QueueInitialize EQU #86BB
PyZ80FT_QueuePushCommand EQU #87FF
PyZ80FT_QueuePushDL EQU #8825
PyZ80FT_QueuePushDescAppend EQU #964C
PyZ80FT_QueuePushDescriptor EQU #92AF
PyZ80FT_QueuePushTemplate EQU #8907
PyZ80FT_ResolveBankKey EQU #88CD
RTypePyABI_Bridge_000 EQU #80A8
RTypePyCompiled_AdvancePitch EQU #8000
