"""Статический компилятор ограниченного Python в переносимое IR и Z80."""

from .diagnostics import CompileError, Diagnostic, SourceSpan
from .assets import (ARGB4444_LE, ASSET_PACK_FORMAT, AssetCompileError,
                     AssetPackBudget, CellAssetPack, CellBankSpec, CellKey,
                     CellSourceKey, PackedCell, compile_cell_assets)
from .ft812_assets import (
    FT812_ARGB4,
    FT812_HYBRID_PACK_FORMAT,
    FT812_PALETTED4444,
    FT812_PALETTE_BYTES,
    FT812_PALETTE_COLORS,
    FT812AssetPackBudget,
    FT812CellAssetPack,
    FT812PackedCell,
    FT812Palette,
    compile_ft812_cell_assets,
)
from .ft812_budget import (FT812Bitmap, FT812BudgetError, FT812BudgetReport,
                           FT812CoprocessorExpansion, FT812DrawCost,
                           FT812Timing, analyze_display_list,
                           expand_coprocessor_stream, validate_display_list)
from .frame_fragment_budget import (
    FrameFragmentBudgetError,
    FrameFragmentBudgetReport,
    RenderFrameShape,
    audit_distance_cmd_text,
    compute_source_bindings,
    contract_requirements,
    current_budget_status,
    inspect_render_frame,
    load_contract,
    prove_frame_fragment_budget,
)
from .manifest import (CallAdapterSpec, CompilerManifest, FT812TargetSpec,
                       FunctionSpec, ParameterSpec, TargetSpec)
from .memory import (MemoryLayout, MemoryLayoutReport, PhysicalAllocation,
                     PhysicalAllocationReport, load_memory_layout,
                     validate_physical_allocations)
from .pipeline import CompilationResult, compile_manifest
from .working_sets import (
    FT812_WORKING_SET_PLAN_FORMAT,
    FT812WorkingSet,
    FT812WorkingSetPlan,
    FT812WorkingSetSpec,
    compile_ft812_working_sets,
)
from .full_hqt3_inventory import (
    FULL_HQT3_INVENTORY_FORMAT,
    FULL_HQT3_INVENTORY_STATUS,
    ConcreteTemplate,
    FullHQT3InventoryError,
    analyze_full_hqt3_inventory,
    concrete_templates_for_pairs,
    fixed_hqt3_bytes,
)

__all__ = [
    "CompilationResult",
    "ARGB4444_LE",
    "ASSET_PACK_FORMAT",
    "AssetCompileError",
    "AssetPackBudget",
    "CompileError",
    "CallAdapterSpec",
    "CellAssetPack",
    "CellBankSpec",
    "CellKey",
    "CellSourceKey",
    "CompilerManifest",
    "Diagnostic",
    "FunctionSpec",
    "FT812Bitmap",
    "FT812_ARGB4",
    "FT812_HYBRID_PACK_FORMAT",
    "FT812_PALETTED4444",
    "FT812_PALETTE_BYTES",
    "FT812_PALETTE_COLORS",
    "FT812AssetPackBudget",
    "FT812BudgetError",
    "FT812BudgetReport",
    "FT812CellAssetPack",
    "FT812CoprocessorExpansion",
    "FT812DrawCost",
    "FT812PackedCell",
    "FT812Palette",
    "FT812Timing",
    "FT812TargetSpec",
    "FT812_WORKING_SET_PLAN_FORMAT",
    "FT812WorkingSet",
    "FT812WorkingSetPlan",
    "FT812WorkingSetSpec",
    "FULL_HQT3_INVENTORY_FORMAT",
    "FULL_HQT3_INVENTORY_STATUS",
    "ConcreteTemplate",
    "FrameFragmentBudgetError",
    "FrameFragmentBudgetReport",
    "FullHQT3InventoryError",
    "MemoryLayout",
    "MemoryLayoutReport",
    "ParameterSpec",
    "PackedCell",
    "PhysicalAllocation",
    "PhysicalAllocationReport",
    "SourceSpan",
    "RenderFrameShape",
    "TargetSpec",
    "analyze_display_list",
    "analyze_full_hqt3_inventory",
    "audit_distance_cmd_text",
    "compile_manifest",
    "compile_cell_assets",
    "compile_ft812_cell_assets",
    "compile_ft812_working_sets",
    "concrete_templates_for_pairs",
    "compute_source_bindings",
    "contract_requirements",
    "current_budget_status",
    "expand_coprocessor_stream",
    "fixed_hqt3_bytes",
    "inspect_render_frame",
    "load_contract",
    "load_memory_layout",
    "validate_physical_allocations",
    "validate_display_list",
    "prove_frame_fragment_budget",
]
