#!/usr/bin/env python3
"""Build seven composite R-Type logo glyphs for FT812 bitmap-cell drawing."""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parents[1]
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

import m72_arcade as m72
import m72_scene
import xbrz_offline
from m72_tile_atlas import pack_argb4444, sprite_layer_rgba, upscale_cell


CAPTURE = ROOT / "Build" / "Arcade" / "MAME" / "title_menu_trace"
OUT = ROOT / "Assets" / "Converted" / "Arcade" / "Atlas"
PNG_OUT = ROOT / "Assets" / "Original" / "Title" / "Font"
INC_OUT = ROOT / "Source" / "ASM" / "generated_m72_title_font.inc"
FRAME = 630
LOG_W, LOG_H = 640, 480
NATIVE_W, NATIVE_H = 384, 256
CELL_W, CELL_H = 107, 120
TEXT_W, TEXT_H = 14, 15
TEXT_FIRST, TEXT_COUNT = 32, 96
TEXT_PALETTES = (6, 14, 15)

# name, native x/y/width/height in the stable reference state.
GLYPHS = (
    ("R", 16, 128, 64, 64),
    ("DOT", 87, 128, 32, 64),
    ("T", 119, 128, 64, 64),
    ("Y", 184, 128, 64, 64),
    ("P", 247, 128, 64, 64),
    ("E", 311, 128, 64, 64),
    ("TM", 344, 184, 24, 24),
)


def main() -> int:
    m72.require_verified()
    regions = m72.assemble_regions()
    prefix = CAPTURE / f"frame_{FRAME:06d}"
    palette = m72_scene.palette_from_ram(
        prefix.with_name(prefix.name + "_palette0.bin").read_bytes(),
        prefix.with_name(prefix.name + "_palette1.bin").read_bytes())
    spriteram = prefix.with_name(prefix.name + "_spriteram.bin").read_bytes()
    native = sprite_layer_rgba(
        spriteram, m72_scene, regions["sprites"],
        len(regions["sprites"]) // 128, palette)
    logical = xbrz_offline.xbrz_expand(native, 6).resize(
        (LOG_W, LOG_H), Image.Resampling.LANCZOS)

    OUT.mkdir(parents=True, exist_ok=True)
    PNG_OUT.mkdir(parents=True, exist_ok=True)
    blob = bytearray()
    for index, (name, x, y, width, height) in enumerate(GLYPHS):
        left = round(x * LOG_W / NATIVE_W)
        top = round(y * LOG_H / NATIVE_H)
        right = round((x + width) * LOG_W / NATIVE_W)
        bottom = round((y + height) * LOG_H / NATIVE_H)
        glyph = Image.new("RGBA", (CELL_W, CELL_H))
        part = logical.crop((left, top, right, bottom))
        if name == "TM":
            # Исправление бага оригинала по решению пользователя (2026-09-14): прямоугольник TM
            # задевает низ буквы E, и при полёте TM к надписи вместе с ним летел кусок E. Пиксели
            # прямоугольника E с ореолом Lanczos (4 пикселя) из глифа TM убираются; сама надпись TM ниже.
            e_name, e_x, e_y, e_width, e_height = GLYPHS[5]
            halo = 4
            e_box = (round(e_x * LOG_W / NATIVE_W) - halo, round(e_y * LOG_H / NATIVE_H) - halo,
                     round((e_x + e_width) * LOG_W / NATIVE_W) + halo,
                     round((e_y + e_height) * LOG_H / NATIVE_H) + halo)
            cut = (max(left, e_box[0]) - left, max(top, e_box[1]) - top,
                   min(right, e_box[2]) - left, min(bottom, e_box[3]) - top)
            if cut[0] < cut[2] and cut[1] < cut[3]:
                part.paste((0, 0, 0, 0), cut)
        glyph.alpha_composite(part, (0, 0))
        glyph.save(PNG_OUT / f"{index}_{name}.png")
        blob += pack_argb4444(glyph)

    logo_bytes = len(blob)
    tile_region = regions["tiles0"]
    for palette_index in TEXT_PALETTES:
        for code in range(TEXT_FIRST, TEXT_FIRST + TEXT_COUNT):
            glyph = upscale_cell(
                m72.decode_tile(tile_region, code), 8, 8, palette,
                256 + palette_index * 16, (TEXT_W, TEXT_H))
            blob += pack_argb4444(glyph)

    path = OUT / "TITLE_FONT_ARGB4444.bin"
    path.write_bytes(blob)
    lines = [
        "; generated by m72_title_font.py — seven composite FT812 cells",
        f"M72_TITLE_FONT_W          EQU {CELL_W}",
        f"M72_TITLE_FONT_H          EQU {CELL_H}",
        f"M72_TITLE_FONT_STRIDE     EQU {CELL_W * 2}",
        f"M72_TITLE_FONT_CELL_BYTES EQU {CELL_W * CELL_H * 2}",
        f"M72_TITLE_FONT_COUNT      EQU {len(GLYPHS)}",
        "M72_TITLE_GLYPH_STATE_BYTES EQU 35",
        f"M72_TITLE_TEXT_W          EQU {TEXT_W}",
        f"M72_TITLE_TEXT_H          EQU {TEXT_H}",
        f"M72_TITLE_TEXT_STRIDE     EQU {TEXT_W * 2}",
        f"M72_TITLE_TEXT_CELL_BYTES EQU {TEXT_W * TEXT_H * 2}",
        f"M72_TITLE_TEXT_FIRST      EQU {TEXT_FIRST}",
        f"M72_TITLE_TEXT_CELL_COUNT EQU {TEXT_COUNT}",
        f"M72_TITLE_TEXT_BASE_OFFSET EQU {logo_bytes}",
        f"M72_TITLE_TEXT_STYLE_BYTES EQU {TEXT_COUNT * TEXT_W * TEXT_H * 2}",
        "M72_TITLE_TEXT_MAX        EQU 96",
        "M72_TITLE_TEXT_STATE_BYTES EQU 384",
        "",
    ]
    INC_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"title font: {len(GLYPHS)} logo cells + "
          f"{len(TEXT_PALETTES) * TEXT_COUNT} text cells, {len(blob)} bytes")
    print(f"blob: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
